// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqhregjhptduqqjktoux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxaHJlZ2pocHRkdXFxamt0b3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDM1OTksImV4cCI6MjA2MzExOTU5OX0.CHvmd3X46EZeRc-7RumRnUnDgUxnuuKxazOjWZ68wEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);